// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateRenderedTemplate(arg1, arg2) {
  return window['go']['main']['App']['CreateRenderedTemplate'](arg1, arg2);
}

export function ListCampaigns() {
  return window['go']['main']['App']['ListCampaigns']();
}

export function ShowCampaign(arg1) {
  return window['go']['main']['App']['ShowCampaign'](arg1);
}
