// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function CreateRenderedTemplate(arg1:string,arg2:string):Promise<string>;

export function ListCampaigns():Promise<Array<service.Campaign>>;

export function ListTemplates():Promise<Array<service.Template>>;

export function ShowCampaign(arg1:string):Promise<service.Campaign>;

export function ShowTemplate(arg1:string):Promise<service.Template>;
